<?php
// $Id: nice_menus.module,v 1.75 2010/10/09 17:19:51 add1sun Exp $

/**
 * @file
 *  Module to enable CSS dropdown and flyout menus.
 *
 * Maintainer: Addison Berry (add1sun)
 * Originally written by Jake Gordon (jakeg)
 */

/**
 * Implementation of hook_help().
 */
function nice_menus_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/settings/modules#description':
      $output .= t('Make drop down/flyout CSS menus for site and admin menus.');
      break;
    case 'admin/settings/nice_menus':
      $output .= t('<p>This is a simple module that enables the site to have drop down/flyout CSS menus for site and admin navigation.</p><p>Remember to activate and configure the menu blocks in !link</p>', array('!link' => l('admin/build/block', 'admin/build/block')));
      break;
  }
  return $output;
}

/**
 * Implementation of hook_form_alter().
 */
function nice_menus_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'system_theme_settings':

      // This is a global setting, so only insert the field
      // on the global settings page.
      if (arg(4) && arg(4) != 'global') {
        return;
      }

      // Have to add a custom submit handler since this form doesn't use
      // the standard system submit handler.
      $form['#submit'][] = 'nice_menus_system_theme_settings_submit';

      // Add global theme setting for a custom CSS file.
      $form['nice_menus_custom_css'] = array(
        '#type' => 'textfield',
        '#title' => t('Path to custom Menu principals CSS file'),
        '#description' => t('To override the default Menu principals CSS layout, enter the path to your custom CSS file.  It should be a relative path from the root of your Drupal install (e.g. sites/all/themes/example/mymenu.css).'),
        '#default_value' => variable_get('nice_menus_custom_css', ''),
        // Field appears below submit buttons without this -- yucky.
        '#weight' => 0,
      );
      break;
  }
}

/**
 * Records the Menu principal custom CSS file per theme.
 */
function nice_menus_system_theme_settings_submit($form, &$form_state) {
  variable_set('nice_menus_custom_css', $form_state['values']['nice_menus_custom_css']);
}

/**
 * Implementation of hook_menu().
 */
function nice_menus_menu() {
  $items['admin/settings/nice_menus'] = array(
    'title' => 'Menu principals',
    'description' => 'Configure Menu principals.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nice_menus_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Settings form as implemented by hook_menu
 */
function nice_menus_admin_settings() {
  $form['nice_menus_number'] = array(
    '#type' => 'textfield',
    '#description' => t('The total number of independent Menu principals blocks you want. Enter a number between 0 and 99. If you set this to 0, you will have no blocks created but you can still use the Menu principals theme functions directly in your theme.'),
    '#default_value' => variable_get('nice_menus_number', '2'),
    '#size' => 2,
  );
  $form['nice_menus_js'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use JavaScript'),
    '#description' => t('This will add Superfish Jquery to Menu principals. This is required for Menu principals to work properly in Internet Explorer.'),
    '#default_value' => variable_get('nice_menus_js', 1),
  );
  $form['nice_menus_sf_options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced: Superfish options'),
    '#description' => t('You can change the default Superfish options by filling out the desired values here. These only take effect if the Use JavaScript box above is checked.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['nice_menus_sf_options']['nice_menus_sf_delay'] = array(
    '#type' => 'textfield',
    '#title' => t('Mouse delay'),
    '#description' => t('The delay in milliseconds that the mouse can remain outside a submenu without it closing.'),
    '#default_value' => variable_get('nice_menus_sf_delay', 800),
    '#size' => 5,
  );
  $form['nice_menus_sf_options']['nice_menus_sf_speed'] = array(
    '#type' => 'select',
    '#title' => t('Animation speed'),
    '#multiple' => FALSE,
    '#description' => t('Speed of the menu open/close animation.'),
    '#options' => array('slow' => t('slow'), 'normal' => t('normal'), 'fast' => t('fast')),
    '#default_value' => variable_get('nice_menus_sf_speed', 1),
     );

  // Custom validation to make sure the user is entering numbers.
  $form['#validate'][] = 'nice_menus_settings_validate';

  return system_settings_form($form);
}

/**
 * Custom validation for the settings form.
 */
function nice_menus_settings_validate($form, &$form_state) {
  $number = $form_state['values']['nice_menus_number'];
  // Check to make sure it is a number and that is a maximum of 2 digits.
  if (!is_numeric($number) || strlen($number) > 2) {
      form_set_error('nice_menus_number', t('You must enter a number from 0 to 99.'));
  }
}

/**
 * Implementation of hook_init().
 *
 * We are adding the JavaScript and CSS here rather than theme_nice_menu
 * because when block caching is enabled none of it would get fired
 * and the menus are unstyled.
 */
function nice_menus_init() {
  // Add Superfish JavaScript, if enabled.
  if (variable_get('nice_menus_js', 1) == 1) {
    // The script, from http://users.tpg.com.au/j_birch/plugins/superfish.
    drupal_add_js(drupal_get_path('module', 'nice_menus') .'/superfish/js/superfish.js');
    // Add the Superfish options variables.
    drupal_add_js(array(
      'nice_menus_options' => array(
        'delay' => variable_get('nice_menus_sf_delay', 800),
        'speed' => variable_get('nice_menus_sf_speed', 1),
        )),'setting');
    // Add the bgIframe plugin.
    drupal_add_js(drupal_get_path('module', 'nice_menus') .'/superfish/js/jquery.bgiframe.min.js');
    // Add the HoverIntent plugin.
    drupal_add_js(drupal_get_path('module', 'nice_menus') .'/superfish/js/jquery.hoverIntent.minified.js');
    // The Menu principals implementation.
    drupal_add_js(drupal_get_path('module', 'nice_menus') .'/nice_menus.js');

    //ajoute le script d'accessibilité

  }
  drupal_add_js(drupal_get_path('module', 'nice_menus') .'/accessible.js');
  	
  // Add main CSS functionality.
  drupal_add_css(drupal_get_path('module', 'nice_menus') .'/nice_menus.css');
  drupal_add_css(drupal_get_path('module', 'nice_menus') .'/nice_menus_sciencespo.css');
  // Add custom CSS layout if specified.
  if ($custom = variable_get('nice_menus_custom_css', '')) {
    drupal_add_css($custom);
  }
  // Fall back to default layout.
  else {
    drupal_add_css(drupal_get_path('module', 'nice_menus') .'/nice_menus_default.css');
  }
}

/**
 * Implementation of hook_block().
 */
function nice_menus_block($op = 'list', $delta = 0, $edit = array()) {
  global $user;

  switch ($op) {
    case 'list':
      for ($i = 1; $i <= variable_get('nice_menus_number', '2'); $i++) {
        $blocks[$i]['info'] = variable_get('nice_menus_name_'. $i, 'Menu principal '. $i) .' (Menu principal)';
        // We have too many things changing per user, per page to cache.
        $blocks[$i]['cache'] = BLOCK_NO_CACHE;
      }
      return $blocks;
    break;

    case 'configure':
      $form['nice_menus_name_'. $delta] = array(
        '#type' => 'textfield',
        '#title' => t('Menu Name'),
        '#default_value' => variable_get('nice_menus_name_'. $delta, 'Menu principal '. $delta),
      );
      $form['nice_menus_menu_'. $delta] = array(
        '#type' => 'select',
        '#title' => t('Menu Parent'),
        '#description' => t('The menu parent from which to show a Menu principal.'),
        '#default_value' => variable_get('nice_menus_menu_'. $delta, 'navigation:0'),
        '#options' => menu_parent_options(menu_get_menus(), 0),
      );
      $form['nice_menus_depth_'. $delta] = array(
       '#type' => 'select',
       '#title' => t('Menu Depth'),
       '#description' => t('The depth of the menu, i.e. the number of child levels starting with the parent selected above. Leave set to -1 to display all children and use 0 to display no children.'),
       '#default_value' => variable_get('nice_menus_depth_'. $delta, -1),
       '#options' => drupal_map_assoc(range(-1, 5))
      );
      $form['nice_menus_type_'. $delta] = array(
        '#type' => 'select',
        '#title' => t('Menu Style'),
        '#description' => t('right: menu items are listed on top of each other and expand to the right') .'<br />'. t('left: menu items are listed on top of each other and expand to the left') .'<br />'. t('down: menu items are listed side by side and expand down'),
        '#default_value' => variable_get('nice_menus_type_'. $delta, 'right'),
        '#options' => drupal_map_assoc(array('right', 'left', 'down')),
      );
      return $form;
    break;

    case 'save':
      variable_set('nice_menus_name_'. $delta, $edit['nice_menus_name_'. $delta]);
      variable_set('nice_menus_menu_'. $delta, $edit['nice_menus_menu_'. $delta]);
      variable_set('nice_menus_depth_'. $delta, $edit['nice_menus_depth_'. $delta]);
      variable_set('nice_menus_type_'. $delta, $edit['nice_menus_type_'. $delta]);
    break;

    case 'view':
      // Build the Menu principal for the block.
      list($menu_name, $mlid) = explode(':', variable_get('nice_menus_menu_'. $delta, 'navigation:0'));
      $direction = variable_get('nice_menus_type_'. $delta, 'right');
      $depth = variable_get('nice_menus_depth_'. $delta, '-1');
      if ($output = theme('nice_menus', $delta, $menu_name, $mlid, $direction, $depth)) {
        $block['content'] = $output['content'];
        if (variable_get('nice_menus_type_'. $delta, 'right') == 'down') {
          $class = 'nice-menu-hide-title';
        }
        else {
          $class = 'nice-menu-show-title';
        }
        // If we're building the navigation block
        // use the same block title logic as menu module.
        if ($output['subject'] == t('Navigation') && $user->uid) {
          $subject = $user->name;
        }
        else {
          $subject = $output['subject'];
        }
        $block['subject'] = '<span class="'. $class .'">'. check_plain($subject) .'</span>';
      }
      else {
        $block['content'] = FALSE;
      }
      return $block;
    break;
  }
}

/**
 * Implementation of hook_theme().
 */
function nice_menus_theme() {
  return array(
    'nice_menus_tree' => array(
      'arguments' => array('menu_name' => NULL, 'mlid' => NULL, 'depth' => -1, 'menu' => NULL),
    ),
    'nice_menus_build' => array(
      'arguments' => array('menu' => NULL,  'depth' => -1, 'trail' => NULL),
    ),
    'nice_menus' => array(
      'arguments' => array('id' => NULL, 'menu_name' => NULL, 'mlid' => NULL, 'direction' => 'right', 'depth' => -1, 'menu' => NULL),
    ),
    'nice_menus_primary_links' => array(
      'arguments' => array('direction' => 'down', 'depth' => -1, 'menu' => NULL),
    ),
    'nice_menus_secondary_links' => array(
      'arguments' => array('direction' => 'down', 'depth' => -1, 'menu' => NULL),
    ),
    // Deprecated theme functions that will be removed in 7.x.
    'nice_menu_tree' => array(
      'arguments' => array('menu_name' => NULL, 'mlid' => NULL, 'depth' => -1, 'menu' => NULL),
    ),
    'nice_menu_build' => array(
      'arguments' => array('menu' => NULL,  'depth' => -1, 'trail' => NULL),
    ),
    'nice_menu' => array(
      'arguments' => array('id' => NULL, 'menu_name' => NULL, 'mlid' => NULL, 'direction' => 'right', 'depth' => -1, 'menu' => NULL),
    ),
    'nice_menu_primary_links' => array(
      'arguments' => array('direction' => 'down', 'depth' => -1, 'menu' => NULL),
    ),
  );
}

/**
 * Builds the active trail from the page's menu data.
 *
 * @param $page_menu
 *   The menu data for a page.
 * @return
 *   An array of parent menu item ids.
 */
function nice_menus_build_page_trail($page_menu) {
  $trail = array();
  foreach ($page_menu as $item) {
    if ($item['link']['in_active_trail']) {
      $trail[] = $item['link']['mlid'];
    }
    if ($item['below']) {
      $trail = array_merge($trail, nice_menus_build_page_trail($item['below']));
    }
  }
  return $trail;
}

/**
 * Builds the final Menu principal.
 *
 * @param $menu_name
 *   The top-level menu name that contains the menu to use (e.g. navigation
 *   or primary-links) for Drupal menus. For custom $menus this is just the
 *   name for menu display.
 * @param $mlid
 *   The menu ID from which to start building the items, i.e. the parent
 *   of the displayed menu.
 * @param $depth
 *   The number of children levels to display. Use -1 to display all children
 *   and use 0 to display no children.
 * @param $menu
 *   Optional. A custom menu array to use for theming -- it should have
 *   the same structure as that returned by menu_tree_all_data().
 * @return
 *   An HTML string of properly nested Menu principal lists.
 */
function theme_nice_menus_tree($menu_name, $mlid = NULL, $depth = -1, $menu = NULL) {
  // Load the full menu array.
  $menu = isset($menu) ? $menu : menu_tree_all_data($menu_name);

  if (isset($menu)) {
    $page_menu = menu_tree_page_data($menu_name);
    $trail = nice_menus_build_page_trail($page_menu);
    unset($page_menu);
  }

  // Allow i18n module to translate strings where available.
  if (module_exists('i18nmenu')) {
    i18nmenu_localize_tree($menu);
  }

  // For custom $menus and menus built all the way from the top-level we
  // don't need to "create" the specific sub-menu and we need to get the title
  // from the $menu_name since there is no "parent item" array.

  // Create the specific menu if we have a mlid.
  if (!empty($mlid)) {
    // Load the parent menu item.
    $item = menu_link_load($mlid);
    $title = check_plain($item['title']);
    // The depth for our parent item.
    $parent_depth = $item['depth'];

    // Narrow down the full menu to the specific sub-tree we need.
    for ($p = 1; $p < 10; $p++) {
      if ($sub_mlid = $item["p$p"]) {
        $subitem = menu_link_load($sub_mlid);
        // Menu sets these ghetto-ass keys in _menu_tree_check_access().
        $menu = $menu[(50000 + $subitem['weight']) .' '. $subitem['title'] .' '. $subitem['mlid']]['below'];
      }
    }
  }
  // Otherwise just set a title and move on.
  else {
    // Get the title from the DB since we don't have it in the $menu.
    $result = db_result(db_query("SELECT title FROM {menu_custom} WHERE menu_name = '%s'", $menu_name));
    $title = check_plain($result);
  }

  $output['content'] = '';
  $output['subject'] = $title;

  if ($menu) {
    // Set the total menu depth counting from this parent if we need it.
    $depth =  ($depth > 0) ? ($parent_depth + $depth) : $depth;
    $output['content'] .= theme('nice_menus_build', $menu, $depth, $trail);
  }

  return $output;
}


$mmlid = 0;
$childrenNum = array();
$childrenFirstColumn = array();
$nbInFirstColumn = array();


function theme_nice_menus_build($menu, $depth = -1, $trail = NULL, $niveau = 1) {
	
	global $mmlid;
	global $childrenNum;
	global $childrenFirstColumn;
	global $nbInFirstColumn;
	global $language;
	// $language->language = NULL;
	global $base_url;
	$menu_niveau_un_cliquable = variable_get('cliquable', 0);

	$curi = explode('/', urldecode(request_uri()));
	$topic = $curi[count($curi) -1];
	if ($topic == '') {
		$topic = 'la-page-d-accueil';
	} else if ($topic == 'fr') {
		$topic = 'la-page-d-accueil';
	} else if ($topic == 'en') {
		$topic = 'homepage';
	}


	$menulid = NULL;
	
	
	foreach ($menu as $menu_item) {
		if (!empty($menu_item['below'])) {
			foreach ($menu_item['below'] as $menu_item_item) {
				if ($menu_item_item['link']['href']) {
					$m = explode('/', drupal_get_path_alias($menu_item_item['link']['href'], $language->language));
					$me = $m[count($m) - 1];
					if($me == $topic){
                  // $menulid = $menu_item['link']['mlid'];
						$menulid = $menu_item['link']['mlid'];
					}
				}
				if (!empty($menu_item_item['below'])) {
					foreach ($menu_item_item['below'] as $menu_item_item_item) {
						if ($menu_item_item_item['link']['href']) {
							$mm = explode('/', drupal_get_path_alias($menu_item_item_item['link']['href'], $language->language));
							$mme = $mm[count($mm) - 1];
							if($mme == $topic){
                        // $menulid = $menu_item['link']['mlid'];
      						$menulid = $menu_item['link']['mlid'];
							}
						}
					}
				}
			}
		}else{
			$mm = explode('/', drupal_get_path_alias($menu_item['link']['href'], $language->language));
			$mme = $mm[count($mm) - 1];
			if($mme == $topic){
            // $menulid = $menu_item['link']['mlid'];
				$menulid = $menu_item['link']['mlid'];
			}			
		}
	}


  $output = '';
  $index = 0;
  $count = 0;
  foreach ($menu as $menu_count) {
    if ($menu_count['link']['hidden'] == 0) {
      $count++;
    }
  }

  //Prepare to count the links so we can mark first, last, odd and even.
	if($niveau == 1) {
		foreach ($menu as $menu_item1) {
			if(!empty($menu_item1['below'])){
				foreach($menu_item1['below'] as $menu_item2) {
					$childrenNum[$menu_item1['link']['mlid']] += 1;
				}
			}
		}
		if($childrenNum){
			foreach ($childrenNum as $key => $val) {
				if($val > 2){
					$childrenFirstColumn[$key] = ceil($val / 2);
					$nbInFirstColumn[$key] = 0;
				}
			}
		}
	}
	
  // Get to building the menu.
  $deuxcol = false;
  foreach ($menu as $menu_item) {
	$mlid = $menu_item['link']['mlid'];
	$plid = $menu_item['link']['plid'];
	
	if($niveau == 1) {
		$mmlid = $mlid;
	}
    // Check to see if it is a visible menu item.
    if (!isset($menu_item['link']['hidden']) || $menu_item['link']['hidden'] == 0) {
      // Check our count and build first, last, odd/even classes.
      $index++;
      $first_class = $index == 1 ? ' first ' : '';
      $oddeven_class = $index % 2 == 0 ? ' even ' : ' odd ';
      $last_class = $index == $count ? ' last ' : '';
      // Build class name based on menu path
      // e.g. to give each menu item individual style.
      // Strip funny symbols.
      $clean_path = str_replace(array('http://', 'www', '<', '>', '&', '=', '?', ':', '.'), '', $menu_item['link']['href']);
      // Convert slashes to dashes.
      $clean_path = str_replace('/', '-', $clean_path);
      $class = 'menu-path-'. $clean_path;
      if ($trail && in_array($mlid, $trail)) {
        $class .= ' active-trail';
      }
      if(strstr($menu_item['link']['href'], 'http')){
         $menu_item['link']['localized_options']['attributes']['target'] = '_blank';
      }
      if($menu_item['link']['localized_options']['attributes']['target'] == '_blank') {
         $menu_item['link']['localized_options']['attributes']['title'] = $menu_item['link']['link_title'].' - '.t("open in new window");
      }

      // If it has children build a nice little tree under it.
      if ((!empty($menu_item['link']['has_children'])) && (!empty($menu_item['below'])) && $depth != 0) {
        // Keep passing children into the function 'til we get them all.
        $children = theme('nice_menus_build', $menu_item['below'], $depth, $trail, $niveau + 1);
        
        // Set the class to parent only of children are displayed.
        $parent_class = ($children && ($menu_item['link']['depth'] <= $depth || $depth == -1)) ? 'menuparent ' : '';
		if($niveau == 2){
			// $nbInFirstColumn[$mmlid] ++;
			$output .= "\t\t\n".'<li class="niveau'.$niveau.' menu-' . $mlid . ' ' . $parent_class . $class . $first_class . $oddeven_class . $last_class .'">'. theme('menu_item_link', $menu_item['link']);
		}else if($niveau == 3){
			$output .= "\t\t\t\n".'<li class="niveau'.$niveau.' menu-' . $mlid . ' ' . $first_class . $oddeven_class . $last_class .'"><span class="puce"></span>'. theme('menu_item_link', $menu_item['link']) ."</li>\n";
		}else if($niveau >= 4){
			continue;
		}else{
			//menu niveau 1 avec enfants
			if($menulid == $mlid) {//page courante
			   $menu_item['link']['localized_options']['attributes']['title'] = $menu_item['link']['localized_options']['attributes']['title'].' '.t('Current section : ').$menu_item['link']['link_title'];
			   if($menu_niveau_un_cliquable == 1) {
   				$output .= "\n".'<li class="active-menu niveau'.$niveau.' menu-' . $mlid . ' ' . $parent_class . $class . $first_class . $oddeven_class . $last_class .' fixed-width">'. theme('menu_item_link', $menu_item['link']);
			   }else{
   				$output .= "\n".'<li class="active-menu niveau'.$niveau.' menu-' . $mlid . ' ' . $parent_class . $class . $first_class . $oddeven_class . $last_class .' fixed-width"><a href="#" class="fixed-width">'. $menu_item['link']['link_title'].'</a>';
			   }
            
			}else{
			   if($menu_niveau_un_cliquable == 1) {
 				   $output .= "\n".'<li class="niveau'.$niveau.' menu-' . $mlid . ' ' . $parent_class . $class . $first_class . $oddeven_class . $last_class .' fixed-width">'. theme('menu_item_link', $menu_item['link']);
			   }else{
				   $output .= "\n".'<li class="niveau'.$niveau.' menu-' . $mlid . ' ' . $parent_class . $class . $first_class . $oddeven_class . $last_class .' fixed-width"><a href="#" class="fixed-width">'. $menu_item['link']['link_title'].'</a>';
			   }
			}
		}
		// Check our depth parameters.
        if ($menu_item['link']['depth'] <= $depth || $depth == -1) {
          // Build the child UL only if children are displayed for the user.
	         if ($children && $niveau == 1) {
				$output .= "\t\t\n<ul>";
				$output .= $children;
				$output .= "\t\t\n</ul>\n";
				$output .= "\t\n</li>";
	         }else if($children && $niveau == 2){
				$output .= '<ul>';
				$output .= $children;
				$output .= "</ul>\n";
				$output .= "\t\t\t\n</li>";
	         }else if($children && $niveau == 3){
				$output .= $children;
		  	}
        }
        // $output .= "</li>\n";
     }
      else {
		if($niveau == 2){
			// $nbInFirstColumn[$mmlid] ++;
			$output .= "\t\t\n".'<li class="niveau'.$niveau.' menu-' . $mlid . ' ' . $class . $first_class . $oddeven_class . $last_class .'">'. theme('menu_item_link', $menu_item['link']) .'</li>'."\n";
		}else if($niveau == 3){
				$output .= "\t\t\t\n".'<li class="niveau'.$niveau.' menu-' . $mlid . ' ' . $first_class . $oddeven_class . $last_class .'"><span class="puce"></span>'. theme('menu_item_link', $menu_item['link']) ."</li>\n";
		}else if($niveau >= 4){
			continue;
		}else{
		
			//niveau 1 sans enfant
			if($menulid == $mlid) {//page courante
			   
			   $menu_item['link']['localized_options']['attributes']['title'] = $menu_item['link']['localized_options']['attributes']['title'].' '.t('Current section : ').$menu_item['link']['link_title'];
				$output .= "\n".'<li class="fixed-width active-menu niveau'.$niveau.' menu-' . $mlid . ' ' . $parent_class . $class . $first_class . $oddeven_class . $last_class .'">'.theme('menu_item_link', $menu_item['link']).'</li>';
			}else{
				$output .= "\n".'<li class="fixed-width niveau'.$niveau.' menu-' . $mlid . ' ' . $parent_class . $class . $first_class . $oddeven_class . $last_class .'">'.theme('menu_item_link', $menu_item['link']).'</li>'."\n";

			}
		}
      }
    }
	

  }

	
  return $output;
}




/**
 * Theme function to allow any menu tree to be themed as a Menu principal.
 *
 * @param $id
 *   The Menu principal ID.
 * @param $menu_name
 *   The top parent menu name from which to build the full menu.
 * @param $mlid
 *   The menu ID from which to build the displayed menu.
 * @param $direction
 *   Optional. The direction the menu expands. Default is 'right'.
 * @param $depth
 *   The number of children levels to display. Use -1 to display all children
 *   and use 0 to display no children.
 * @param $menu
 *   Optional. A custom menu array to use for theming --
 *   it should have the same structure as that returned
 *  by menu_tree_all_data(). Default is the standard menu tree.
 * @return
 *   An HTML string of Menu principal links.
 */
function theme_nice_menus($id, $menu_name, $mlid, $direction = 'right', $depth = -1, $menu = NULL) {
  $output = array();

  if ($menu_tree = theme('nice_menus_tree', $menu_name, $mlid, $depth, $menu)) {
    if ($menu_tree['content']) {
      $output['content'] = '<ul class="nice-menu nice-menu-'. $direction .'" id="nice-menu-'. $id .'">'. $menu_tree['content'] .'</ul>'."\n";
      $output['subject'] = $menu_tree['subject'];
    }
  }
  return $output;
}

/**
 * Theme primary links as Menu principals.
 *
 * @param $direction
 *   Optional. The direction the menu expands. Default is 'down'.
 * @param $depth
 *   The number of children levels to display. Use -1 to display all children
 *   and use 0 to display no children.
 * @param $menu
 *   Optional. A custom menu array to use for theming --
 *   it should have the same structure as that returned
 *   by menu_tree_all_data(). Default is the standard menu tree.
 * @return
 *   An HTML string of Menu principal primary links.
 */
function theme_nice_menus_primary_links($direction = 'down', $depth = -1, $menu = NULL) {
  $menu_name = variable_get('menu_primary_links_source', 'primary-links');
  $output = theme('nice_menus', 0, $menu_name, 0, $direction, $depth, $menu);
  return $output['content'];
}

/**
 * Theme secondary links as nice menus.
 *
 * @param $direction
 *   Optional. The direction the menu expands. Default is 'down'.
 * @param $depth
 *   The number of children levels to display. Use -1 to display all children
 *   and use 0 to display no children.
 * @param $menu
 *   Optional. A custom menu array to use for theming --
 *   it should have the same structure as that returned
 *   by menu_tree_all_data(). Default is the standard menu tree.
 * @return
 *   An HTML string of nice menu secondary links.
 */
function theme_nice_menus_secondary_links($direction = 'down', $depth = -1, $menu = NULL) {
  $menu_name = variable_get('menu_secondary_links_source', 'secondary-links');
  $output = theme('nice_menus', 0, $menu_name, 0, $direction, $depth, $menu);
  return $output['content'];
}
